# fly.toml app configuration file generated for noteeees on 2023-08-30T14:16:18+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "noteeees"
primary_region = "hkg"

[build]

[env]
  PORT = "3000" # add this

[http_service]
  internal_port = 3000 # ensure that this is same as PORT
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
